// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Root() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Tic Tac Toe</title><link rel=\"stylesheet\" href=\"/static/tailwind.css\"></head><body class=\"bg-gradient-to-br from-yellow-300 to-orange-400 min-h-screen flex items-center justify-center\"><!-- New Game Section --><div class=\"text-center p-6 bg-white rounded-lg shadow-lg max-w-sm\"><h1 class=\"text-3xl font-semibold text-gray-800 mb-4\">Tic Tac Toe</h1><p class=\"text-gray-600 text-sm mb-5\">Challenge a friend or play against the computer.</p><!-- Form --><form class=\"w-full max-w-xs\" action=\"/new_game\" method=\"post\"><div class=\"space-y-3\"><input type=\"text\" placeholder=\"Player 1 Name\" class=\"input input-bordered input-sm w-full max-w-xs\"> <input type=\"text\" placeholder=\"Player 2 Name\" class=\"input input-bordered input-sm w-full max-w-xs\"> <button class=\"btn btn-accent btn-sm w-full\" type=\"submit\">Start Game</button></div></form></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
